# Generated by Django 5.1.2 on 2024-10-15 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
