# Generated by Django 5.1.2 on 2024-10-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
